### ISSUE TITLE
Unexpected end of input

### ISSUE THREAD

**Issue by kiranmca04** [75lb/app-usage-stats#1]
Hi,
I am new to this.  app-usage-stats package is part of our application.  When building the app we are getting this error.  It was working fine earlier.  Nothing has changed suddenly today it is giving these errors.  Any inputs please? 

I have uninstalled all the packages including node, npm and installed freshly. 

/Users/myName/Documents/TestUI/rpd/vCCAP/node_modules/xdGulpTasks/node_modules/gulp-jsdoc-to-markdown/node_modules/jsdoc-to-markdown/node_modules/jsdoc2md-stats/node_modules/app-usage-stats/es5/lib/app-usage-stats.js:195
          throw err;
                ^
SyntaxError: Unexpected end of input
    at Object.parse (native)
    at AppUsageStats.loadSync (/Users/myName/Documents/TestUI/rpd/vCCAP/node_modules/xdGulpTasks/node_modules/gulp-jsdoc-to-markdown/node_modules/jsdoc-to-markdown/node_modules/jsdoc2md-stats/node_modules/app-usage-stats/es5/lib/app-usage-stats.js:191:26)
    at new JsdocToMarkdownStats (/Users/myName/Documents/TestUI/rpd/vCCAP/node_modules/xdGulpTasks/node_modules/gulp-jsdoc-to-markdown/node_modules/jsdoc-to-markdown/node_modules/jsdoc2md-stats/es5/jsdoc2md-stats.js:63:20)
    at Object.<anonymous> (/Users/myName/Documents/TestUI/rpd/vCCAP/node_modules/xdGulpTasks/node_modules/gulp-jsdoc-to-markdown/node_modules/jsdoc-to-markdown/lib/jsdoc-to-markdown.js:60:17)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)

Kiran

**Comment by 75lb** [comment]
fixed in app-usage-stats v0.4.1 - please update or reinstall your npm modules and try again.. the issue was your stats data had somehow become corrupted.
